### ISSUE TITLE
Support or ignore attributes on type parameters

### ISSUE THREAD

**Issue by jskeet** [JakeGinnivan/ApiApprover#63]
C# 8 uses attributes on type parameters for nullability, and this causes problems for the tool at the moment.

Example:

Foo.csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <NullableContextOptions>enable</NullableContextOptions>
  </PropertyGroup>
</Project>
```

Class1.cs:

```csharp
namespace Foo
{
    public class Class1<T> where T : class
    {
    }
}
```

Invocation:

```sh
$ generate-public-api --project-path Foo.csproj --target-frameworks netcoreapp3.0 --assembly Foo.dll
```

Error:

```text
Failed: System.Exception: dotnet exit code -532462766. Directory: C:\Users\skeet\AppData\Local\Temp\evz1pbfi.oin. Args: run --configuration Release --framework netcoreapp3.0 -- C:\Users\skeet\AppData\Local\Temp\evz1pbfi.oin\bin\Release\netcoreapp3.0\Foo.dll C:\Users\skeet\AppData\Local\Temp\evz1pbfi.oin\bin\Release\netcoreapp3.0\Foo.netcoreapp3.0.received.txt c:\Users\jon\Test\Foo. Output: . Error:
Unhandled Exception: System.NotImplementedException: Attributes on type parameters is not supported. And weird
   at PublicApiGenerator.ApiGenerator.PopulateGenericParameters(IGenericParameterProvider publicType, CodeTypeParameterCollection parameters)
   at PublicApiGenerator.ApiGenerator.CreateTypeDeclaration(TypeDefinition publicType, String[] whitelistedNamespacePrefixes, HashSet`1 excludeAttributes)
   at PublicApiGenerator.ApiGenerator.CreatePublicApiForAssembly(AssemblyDefinition assembly, Func`2 shouldIncludeType, Boolean shouldIncludeAssemblyAttributes, String[] whitelistedNamespacePrefixes, HashSet`1 excludeAttributes)
   at PublicApiGenerator.ApiGenerator.GeneratePublicApi(Assembly assembly, Type[] includeTypes, Boolean shouldIncludeAssemblyAttributes, String[] whitelistedNamespacePrefixes, String[] excludeAttributes)
   at Program.Main(String[] args) in C:\Users\skeet\AppData\Local\Temp\evz1pbfi.oin\Program.cs:line 14

   at PublicApiGenerator.Tool.Program.RunDotnet(String workingArea, Boolean verbose, String arguments) in C:\projects\apiapprover\src\PublicApiGenerator.Tool\Program.cs:line 136
   at PublicApiGenerator.Tool.Program.GeneratePublicApi(String assembly, String package, String workingArea, String framework, String outputDirectory, Boolean verbose) in C:\projects\apiapprover\src\PublicApiGenerator.Tool\Program.cs:line 93
   at PublicApiGenerator.Tool.Program.Main(String targetFrameworks, String assembly, String projectPath, String package, String packageVersion, String generatorVersion, String workingDirectory, String outputDirectory, Boolean verbose, Boolean leaveArtifacts) in C:\projects\apiapprover\src\PublicApiGenerator.Tool\Program.cs:line 56
```

**Comment by danielmarbach** [comment]
You are such a troublemaker 😉🤣 I hope I can give this a look before my long vacation break

**Comment by jskeet** [comment]
No hurry!

**Comment by danielmarbach** [comment]
Looks like Mono.Cecil is working on this

https://github.com/jbevain/cecil/pull/594

related to

https://github.com/dotnet/roslyn/issues/29997

**Comment by danielmarbach** [comment]
Ok I have a workaround that I can push soon and I also found a way of at least presenting, for now, the nullable attributes. After that, we can start looking into pretty printing those attributes

**Comment by danielmarbach** [comment]
This enables for now support of Type attributes

https://github.com/JakeGinnivan/ApiApprover/pull/65

I can release this as a patch next week

**Comment by danielmarbach** [comment]
Done. Should be available on nuget soonish

**Comment by jskeet** [comment]
Thanks, you're a star :)
